"""empty message

Revision ID: e2b9963303bb
Revises: 4e11868afb1d
Create Date: 2021-05-25 20:15:16.971857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b9963303bb'
down_revision = '4e11868afb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('places_name_key', 'places', type_='unique')
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.create_unique_constraint('places_name_key', 'places', ['name'])
    # ### end Alembic commands ###
