"""empty message

Revision ID: 967a65d92d22
Revises: 
Create Date: 2021-05-03 16:42:09.522839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967a65d92d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('street_house_number', sa.String(length=255), nullable=False),
    sa.Column('postcode', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email_adress', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('wifi_available', sa.String(), nullable=True),
    sa.Column('toilet_available', sa.String(), nullable=True),
    sa.Column('power_slots_available', sa.String(), nullable=True),
    sa.Column('alcohol_available', sa.String(), nullable=True),
    sa.Column('vegan_alternatives_available', sa.String(), nullable=True),
    sa.Column('laptops_allowed', sa.String(), nullable=True),
    sa.Column('open_for_takeaway', sa.String(), nullable=True),
    sa.Column('open_for_delivery', sa.String(), nullable=True),
    sa.Column('price_espresso', sa.String(), nullable=True),
    sa.Column('price_filter_coffee', sa.String(), nullable=True),
    sa.Column('price_cappuccino', sa.String(), nullable=True),
    sa.Column('wifi_network_name', sa.String(length=255), nullable=True),
    sa.Column('wifi_network_password', sa.String(length=255), nullable=True),
    sa.Column('food_options', sa.String(length=255), nullable=True),
    sa.Column('picture_urls', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('data_privacy_accepted', sa.Boolean(), nullable=False),
    sa.Column('email_marketing_accepted', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('opening_hours',
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('opening_id')
    )
    op.create_table('placestoenduser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('post_date', sa.Date(), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('poast_image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stars_number', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('helpful_questions', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('posts')
    op.drop_table('placestoenduser')
    op.drop_table('opening_hours')
    op.drop_table('users')
    op.drop_table('places')
    # ### end Alembic commands ###
